/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculadora;

/**
 *
 * @author LENOVO
 */
import java.lang.Math;
public class diseño extends javax.swing.JFrame {

    /**
     * Creates new form diseño
     */
    public diseño() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        num7 = new javax.swing.JButton();
        num9 = new javax.swing.JButton();
        num8 = new javax.swing.JButton();
        num5 = new javax.swing.JButton();
        num4 = new javax.swing.JButton();
        num6 = new javax.swing.JButton();
        num2 = new javax.swing.JButton();
        num1 = new javax.swing.JButton();
        num3 = new javax.swing.JButton();
        numlog = new javax.swing.JButton();
        num0 = new javax.swing.JButton();
        numexponencial = new javax.swing.JButton();
        nummultiplicacion = new javax.swing.JButton();
        numsuma = new javax.swing.JButton();
        numresta = new javax.swing.JButton();
        numdivision = new javax.swing.JButton();
        numigual = new javax.swing.JButton();
        resul = new javax.swing.JLabel();
        resul2 = new javax.swing.JLabel();
        resu3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        num7.setText("7");
        num7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num7ActionPerformed(evt);
            }
        });

        num9.setText("9");
        num9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num9ActionPerformed(evt);
            }
        });

        num8.setText("8");
        num8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num8ActionPerformed(evt);
            }
        });

        num5.setText("5");
        num5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num5ActionPerformed(evt);
            }
        });

        num4.setText("4");
        num4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num4ActionPerformed(evt);
            }
        });

        num6.setText("6");
        num6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num6ActionPerformed(evt);
            }
        });

        num2.setText("2");
        num2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num2ActionPerformed(evt);
            }
        });

        num1.setText("1");
        num1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num1ActionPerformed(evt);
            }
        });

        num3.setText("3");
        num3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num3ActionPerformed(evt);
            }
        });

        numlog.setText("Log");
        numlog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numlogActionPerformed(evt);
            }
        });

        num0.setText("0");
        num0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num0ActionPerformed(evt);
            }
        });

        numexponencial.setText("10^x");
        numexponencial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numexponencialActionPerformed(evt);
            }
        });

        nummultiplicacion.setText("*");
        nummultiplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nummultiplicacionActionPerformed(evt);
            }
        });

        numsuma.setText("+");
        numsuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numsumaActionPerformed(evt);
            }
        });

        numresta.setText("-");
        numresta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numrestaActionPerformed(evt);
            }
        });

        numdivision.setText("/");
        numdivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numdivisionActionPerformed(evt);
            }
        });

        numigual.setText("=");
        numigual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numigualActionPerformed(evt);
            }
        });

        resul.setBackground(new java.awt.Color(255, 255, 255));
        resul.setText("Insert");

        resul2.setBackground(new java.awt.Color(255, 255, 255));
        resul2.setText("Insert");

        resu3.setBackground(new java.awt.Color(255, 255, 255));
        resu3.setText("Insert");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(num7)
                                .addGap(12, 12, 12)
                                .addComponent(num8)
                                .addGap(22, 22, 22)
                                .addComponent(num9)
                                .addGap(18, 18, 18)
                                .addComponent(numsuma))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(num4)
                                .addGap(12, 12, 12)
                                .addComponent(num5)
                                .addGap(22, 22, 22)
                                .addComponent(num6)
                                .addGap(18, 18, 18)
                                .addComponent(numresta))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(num1)
                                .addGap(12, 12, 12)
                                .addComponent(num2)
                                .addGap(22, 22, 22)
                                .addComponent(num3)
                                .addGap(18, 18, 18)
                                .addComponent(nummultiplicacion))
                            .addComponent(resu3, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(resul, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(resul2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(numigual, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(num0)
                            .addGap(7, 7, 7)
                            .addComponent(numlog)
                            .addGap(7, 7, 7)
                            .addComponent(numexponencial)
                            .addGap(12, 12, 12)
                            .addComponent(numdivision))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resul, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resul2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(resu3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(num7)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(num8)
                        .addComponent(num9)
                        .addComponent(numsuma)))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(num4)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(num5)
                        .addComponent(num6)
                        .addComponent(numresta)))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(num1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(num2)
                        .addComponent(num3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(nummultiplicacion)))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(num0)
                    .addComponent(numlog)
                    .addComponent(numexponencial)
                    .addComponent(numdivision))
                .addGap(18, 18, 18)
                .addComponent(numigual)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 250, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    double nume1=0,nume2=0,resultado=0;
    String n1="",n2="";
    int operacion=0;
    char op;
    private void numexponencialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numexponencialActionPerformed
      
      operacion+=1;
    op='^';
    }//GEN-LAST:event_numexponencialActionPerformed

    private void num7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num7ActionPerformed
         if(operacion>0){
    n2+="7";
    resul2.setText(n2);
    }else{
    n1+="7";
    resul.setText(n1);
        }
    }//GEN-LAST:event_num7ActionPerformed

    private void num4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num4ActionPerformed
             if(operacion>0){
    n2+="4";
    resul2.setText(n2);
    }else{
    n1+="4";
    resul.setText(n1);
        }
    }//GEN-LAST:event_num4ActionPerformed

    private void numsumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numsumaActionPerformed
    operacion+=1;
    op='+';
       
   

    
    }//GEN-LAST:event_numsumaActionPerformed

    private void num1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num1ActionPerformed
        // TODO add your handling code here:
          if(operacion>0){
    n2+="1";
    resul2.setText(n2);
    }else{
    n1+="1";
    resul.setText(n1);
        }
    }//GEN-LAST:event_num1ActionPerformed

    private void num2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num2ActionPerformed
        // TODO add your handling code here:
          if(operacion>0){
    n2+="2";
    resul2.setText(n2);
    }else{
    n1+="2";
    resul.setText(n1);
        }
    }//GEN-LAST:event_num2ActionPerformed

    private void num3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num3ActionPerformed
      if(operacion>0){
    n2+="3";
    resul2.setText(n2);
    }else{
    n1+="3";
    resul.setText(n1);
        }
    }//GEN-LAST:event_num3ActionPerformed

    private void num5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num5ActionPerformed
       if(operacion>0){
    n2+="5";
    resul2.setText(n2);
    }else{
    n1+="5";
    resul.setText(n1);
        }
    }//GEN-LAST:event_num5ActionPerformed

    private void num6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num6ActionPerformed
   if(operacion>0){
    n2+="6";
    resul2.setText(n2);
    }else{
    n1+="6";
    resul.setText(n1);
        }
    }//GEN-LAST:event_num6ActionPerformed

    private void num9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num9ActionPerformed
           if(operacion>0){
    n2+="9";
    resul2.setText(n2);
    }else{
    n1+="9";
    resul.setText(n1);
        }
    }//GEN-LAST:event_num9ActionPerformed

    private void num0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num0ActionPerformed
          if(operacion>0){
    n2+="4";
    resul2.setText(n2);
    }else{
    n1+="4";
    resul.setText(n1);
        }

    }//GEN-LAST:event_num0ActionPerformed

    private void numrestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numrestaActionPerformed
        // TODO add your handling code here:
        operacion+=1;
    op='-';
    }//GEN-LAST:event_numrestaActionPerformed

    private void nummultiplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nummultiplicacionActionPerformed
     operacion+=1;
    op='*';
    }//GEN-LAST:event_nummultiplicacionActionPerformed

    private void numdivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numdivisionActionPerformed
   operacion+=1;
    op='/';

    }//GEN-LAST:event_numdivisionActionPerformed

    private void numigualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numigualActionPerformed
        // TODO add your handling code here:
        nume1=Double.parseDouble(n1);
        nume2=Double.parseDouble(n2);
        if (op=='+') {
            resultado=nume1+nume2;
        }else if(op=='*'){
            resultado=nume1*nume2;
        }else if(op=='-'){
            resultado=nume1-nume2;
        }else if(op=='/'){
            resultado=nume1/nume2;
        }else if(op=='^'){
            resultado=Math.pow(10, nume1);
        }else if(op=='L'){
            resultado=Math.log10(nume1);
        }
        resu3.setText(String.valueOf(resultado));
    }//GEN-LAST:event_numigualActionPerformed

    private void numlogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numlogActionPerformed
        operacion+=1;
    op='L';
    }//GEN-LAST:event_numlogActionPerformed

    private void num8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num8ActionPerformed
          if(operacion>0){
    n2+="8";
    resul2.setText(n2);
    }else{
    n1+="8";
    resul.setText(n1);
        }
    }//GEN-LAST:event_num8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(diseño.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(diseño.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(diseño.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(diseño.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new diseño().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton num0;
    private javax.swing.JButton num1;
    private javax.swing.JButton num2;
    private javax.swing.JButton num3;
    private javax.swing.JButton num4;
    private javax.swing.JButton num5;
    private javax.swing.JButton num6;
    private javax.swing.JButton num7;
    private javax.swing.JButton num8;
    private javax.swing.JButton num9;
    private javax.swing.JButton numdivision;
    private javax.swing.JButton numexponencial;
    private javax.swing.JButton numigual;
    private javax.swing.JButton numlog;
    private javax.swing.JButton nummultiplicacion;
    private javax.swing.JButton numresta;
    private javax.swing.JButton numsuma;
    private javax.swing.JLabel resu3;
    private javax.swing.JLabel resul;
    private javax.swing.JLabel resul2;
    // End of variables declaration//GEN-END:variables
}
